version: '3.8'

services:
    app:
        build:
            context: .
        container_name: laravel_app
        volumes:
            - .:/var/www
        depends_on:
            - php
        networks:
            - laravel

    php:
        image: php:8.1-fpm
        container_name: php
        volumes:
            - .:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        depends_on:
            - php
        networks:
            - laravel

networks:
    laravel:
